// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf C++ Version: 5.29.3

#include "message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace game {

inline constexpr WaitingPacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        waiting_number_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WaitingPacket::WaitingPacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WaitingPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WaitingPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WaitingPacketDefaultTypeInternal() {}
  union {
    WaitingPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WaitingPacketDefaultTypeInternal _WaitingPacket_default_instance_;

inline constexpr ChatPacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        session_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ChatPacket::ChatPacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChatPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatPacketDefaultTypeInternal() {}
  union {
    ChatPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatPacketDefaultTypeInternal _ChatPacket_default_instance_;

inline constexpr GamePacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_{static_cast< ::game::PacketType >(0)},
        payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR GamePacket::GamePacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GamePacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GamePacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GamePacketDefaultTypeInternal() {}
  union {
    GamePacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GamePacketDefaultTypeInternal _GamePacket_default_instance_;
}  // namespace game
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_message_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_message_2eproto = nullptr;
const ::uint32_t
    TableStruct_message_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::game::GamePacket, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::game::GamePacket, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::game::GamePacket, _impl_.type_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::game::GamePacket, _impl_.payload_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::game::ChatPacket, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::game::ChatPacket, _impl_.session_id_),
        PROTOBUF_FIELD_OFFSET(::game::ChatPacket, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::game::WaitingPacket, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::game::WaitingPacket, _impl_.waiting_number_),
        PROTOBUF_FIELD_OFFSET(::game::WaitingPacket, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::game::GamePacket)},
        {12, -1, -1, sizeof(::game::ChatPacket)},
        {22, -1, -1, sizeof(::game::WaitingPacket)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::game::_GamePacket_default_instance_._instance,
    &::game::_ChatPacket_default_instance_._instance,
    &::game::_WaitingPacket_default_instance_._instance,
};
const char descriptor_table_protodef_message_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rmessage.proto\022\004game\"\201\001\n\nGamePacket\022\036\n\004"
    "type\030\001 \001(\0162\020.game.PacketType\022 \n\004chat\030\002 \001"
    "(\0132\020.game.ChatPacketH\000\022&\n\007waiting\030\003 \001(\0132"
    "\023.game.WaitingPacketH\000B\t\n\007payload\"1\n\nCha"
    "tPacket\022\022\n\nsession_id\030\001 \001(\005\022\017\n\007message\030\002"
    " \001(\t\"8\n\rWaitingPacket\022\026\n\016waiting_number\030"
    "\001 \001(\005\022\017\n\007message\030\002 \001(\t*-\n\nPacketType\022\010\n\004"
    "NONE\020\000\022\010\n\004CHAT\020\001\022\013\n\007WAITING\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_message_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_message_2eproto = {
    false,
    false,
    317,
    descriptor_table_protodef_message_2eproto,
    "message.proto",
    &descriptor_table_message_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_message_2eproto::offsets,
    file_level_enum_descriptors_message_2eproto,
    file_level_service_descriptors_message_2eproto,
};
namespace game {
const ::google::protobuf::EnumDescriptor* PacketType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_message_2eproto);
  return file_level_enum_descriptors_message_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PacketType_internal_data_[] = {
    196608u, 0u, };
bool PacketType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class GamePacket::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::game::GamePacket, _impl_._oneof_case_);
};

void GamePacket::set_allocated_chat(::game::ChatPacket* chat) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (chat) {
    ::google::protobuf::Arena* submessage_arena = chat->GetArena();
    if (message_arena != submessage_arena) {
      chat = ::google::protobuf::internal::GetOwnedMessage(message_arena, chat, submessage_arena);
    }
    set_has_chat();
    _impl_.payload_.chat_ = chat;
  }
  // @@protoc_insertion_point(field_set_allocated:game.GamePacket.chat)
}
void GamePacket::set_allocated_waiting(::game::WaitingPacket* waiting) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (waiting) {
    ::google::protobuf::Arena* submessage_arena = waiting->GetArena();
    if (message_arena != submessage_arena) {
      waiting = ::google::protobuf::internal::GetOwnedMessage(message_arena, waiting, submessage_arena);
    }
    set_has_waiting();
    _impl_.payload_.waiting_ = waiting;
  }
  // @@protoc_insertion_point(field_set_allocated:game.GamePacket.waiting)
}
GamePacket::GamePacket(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.GamePacket)
}
inline PROTOBUF_NDEBUG_INLINE GamePacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::game::GamePacket& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

GamePacket::GamePacket(
    ::google::protobuf::Arena* arena,
    const GamePacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GamePacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.type_ = from._impl_.type_;
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kChat:
        _impl_.payload_.chat_ = ::google::protobuf::Message::CopyConstruct<::game::ChatPacket>(arena, *from._impl_.payload_.chat_);
        break;
      case kWaiting:
        _impl_.payload_.waiting_ = ::google::protobuf::Message::CopyConstruct<::game::WaitingPacket>(arena, *from._impl_.payload_.waiting_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:game.GamePacket)
}
inline PROTOBUF_NDEBUG_INLINE GamePacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void GamePacket::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
GamePacket::~GamePacket() {
  // @@protoc_insertion_point(destructor:game.GamePacket)
  SharedDtor(*this);
}
inline void GamePacket::SharedDtor(MessageLite& self) {
  GamePacket& this_ = static_cast<GamePacket&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void GamePacket::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:game.GamePacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kChat: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.chat_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.chat_);
      }
      break;
    }
    case kWaiting: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.waiting_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.waiting_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* GamePacket::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GamePacket(arena);
}
constexpr auto GamePacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GamePacket),
                                            alignof(GamePacket));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GamePacket::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GamePacket_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GamePacket::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GamePacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GamePacket::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GamePacket>(), &GamePacket::ByteSizeLong,
            &GamePacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GamePacket, _impl_._cached_size_),
        false,
    },
    &GamePacket::kDescriptorMethods,
    &descriptor_table_message_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GamePacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 2, 0, 2> GamePacket::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::game::GamePacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .game.PacketType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GamePacket, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GamePacket, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .game.PacketType type = 1;
    {PROTOBUF_FIELD_OFFSET(GamePacket, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .game.ChatPacket chat = 2;
    {PROTOBUF_FIELD_OFFSET(GamePacket, _impl_.payload_.chat_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .game.WaitingPacket waiting = 3;
    {PROTOBUF_FIELD_OFFSET(GamePacket, _impl_.payload_.waiting_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::game::ChatPacket>()},
    {::_pbi::TcParser::GetTable<::game::WaitingPacket>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GamePacket::Clear() {
// @@protoc_insertion_point(message_clear_start:game.GamePacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0;
  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GamePacket::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GamePacket& this_ = static_cast<const GamePacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GamePacket::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GamePacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:game.GamePacket)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .game.PacketType type = 1;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_type(), target);
          }

          switch (this_.payload_case()) {
            case kChat: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  2, *this_._impl_.payload_.chat_, this_._impl_.payload_.chat_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kWaiting: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  3, *this_._impl_.payload_.waiting_, this_._impl_.payload_.waiting_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:game.GamePacket)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GamePacket::ByteSizeLong(const MessageLite& base) {
          const GamePacket& this_ = static_cast<const GamePacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GamePacket::ByteSizeLong() const {
          const GamePacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:game.GamePacket)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .game.PacketType type = 1;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
          }
          switch (this_.payload_case()) {
            // .game.ChatPacket chat = 2;
            case kChat: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.chat_);
              break;
            }
            // .game.WaitingPacket waiting = 3;
            case kWaiting: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.waiting_);
              break;
            }
            case PAYLOAD_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GamePacket::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GamePacket*>(&to_msg);
  auto& from = static_cast<const GamePacket&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:game.GamePacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kChat: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.chat_ =
              ::google::protobuf::Message::CopyConstruct<::game::ChatPacket>(arena, *from._impl_.payload_.chat_);
        } else {
          _this->_impl_.payload_.chat_->MergeFrom(from._internal_chat());
        }
        break;
      }
      case kWaiting: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.waiting_ =
              ::google::protobuf::Message::CopyConstruct<::game::WaitingPacket>(arena, *from._impl_.payload_.waiting_);
        } else {
          _this->_impl_.payload_.waiting_->MergeFrom(from._internal_waiting());
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GamePacket::CopyFrom(const GamePacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.GamePacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GamePacket::InternalSwap(GamePacket* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata GamePacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ChatPacket::_Internal {
 public:
};

ChatPacket::ChatPacket(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.ChatPacket)
}
inline PROTOBUF_NDEBUG_INLINE ChatPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::game::ChatPacket& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

ChatPacket::ChatPacket(
    ::google::protobuf::Arena* arena,
    const ChatPacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ChatPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.session_id_ = from._impl_.session_id_;

  // @@protoc_insertion_point(copy_constructor:game.ChatPacket)
}
inline PROTOBUF_NDEBUG_INLINE ChatPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void ChatPacket::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.session_id_ = {};
}
ChatPacket::~ChatPacket() {
  // @@protoc_insertion_point(destructor:game.ChatPacket)
  SharedDtor(*this);
}
inline void ChatPacket::SharedDtor(MessageLite& self) {
  ChatPacket& this_ = static_cast<ChatPacket&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ChatPacket::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ChatPacket(arena);
}
constexpr auto ChatPacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ChatPacket),
                                            alignof(ChatPacket));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ChatPacket::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ChatPacket_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ChatPacket::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ChatPacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ChatPacket::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ChatPacket>(), &ChatPacket::ByteSizeLong,
            &ChatPacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ChatPacket, _impl_._cached_size_),
        false,
    },
    &ChatPacket::kDescriptorMethods,
    &descriptor_table_message_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ChatPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 31, 2> ChatPacket::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::game::ChatPacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ChatPacket, _impl_.message_)}},
    // int32 session_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ChatPacket, _impl_.session_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ChatPacket, _impl_.session_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 session_id = 1;
    {PROTOBUF_FIELD_OFFSET(ChatPacket, _impl_.session_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(ChatPacket, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\0\7\0\0\0\0\0"
    "game.ChatPacket"
    "message"
  }},
};

PROTOBUF_NOINLINE void ChatPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:game.ChatPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.session_id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ChatPacket::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ChatPacket& this_ = static_cast<const ChatPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ChatPacket::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ChatPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:game.ChatPacket)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 session_id = 1;
          if (this_._internal_session_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_session_id(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "game.ChatPacket.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:game.ChatPacket)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ChatPacket::ByteSizeLong(const MessageLite& base) {
          const ChatPacket& this_ = static_cast<const ChatPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ChatPacket::ByteSizeLong() const {
          const ChatPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:game.ChatPacket)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // int32 session_id = 1;
            if (this_._internal_session_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_session_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ChatPacket::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ChatPacket*>(&to_msg);
  auto& from = static_cast<const ChatPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game.ChatPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_session_id() != 0) {
    _this->_impl_.session_id_ = from._impl_.session_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ChatPacket::CopyFrom(const ChatPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.ChatPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ChatPacket::InternalSwap(ChatPacket* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.session_id_, other->_impl_.session_id_);
}

::google::protobuf::Metadata ChatPacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WaitingPacket::_Internal {
 public:
};

WaitingPacket::WaitingPacket(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.WaitingPacket)
}
inline PROTOBUF_NDEBUG_INLINE WaitingPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::game::WaitingPacket& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

WaitingPacket::WaitingPacket(
    ::google::protobuf::Arena* arena,
    const WaitingPacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WaitingPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.waiting_number_ = from._impl_.waiting_number_;

  // @@protoc_insertion_point(copy_constructor:game.WaitingPacket)
}
inline PROTOBUF_NDEBUG_INLINE WaitingPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void WaitingPacket::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.waiting_number_ = {};
}
WaitingPacket::~WaitingPacket() {
  // @@protoc_insertion_point(destructor:game.WaitingPacket)
  SharedDtor(*this);
}
inline void WaitingPacket::SharedDtor(MessageLite& self) {
  WaitingPacket& this_ = static_cast<WaitingPacket&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* WaitingPacket::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) WaitingPacket(arena);
}
constexpr auto WaitingPacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WaitingPacket),
                                            alignof(WaitingPacket));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull WaitingPacket::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_WaitingPacket_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &WaitingPacket::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<WaitingPacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &WaitingPacket::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<WaitingPacket>(), &WaitingPacket::ByteSizeLong,
            &WaitingPacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(WaitingPacket, _impl_._cached_size_),
        false,
    },
    &WaitingPacket::kDescriptorMethods,
    &descriptor_table_message_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* WaitingPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 34, 2> WaitingPacket::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::game::WaitingPacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(WaitingPacket, _impl_.message_)}},
    // int32 waiting_number = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WaitingPacket, _impl_.waiting_number_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(WaitingPacket, _impl_.waiting_number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 waiting_number = 1;
    {PROTOBUF_FIELD_OFFSET(WaitingPacket, _impl_.waiting_number_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(WaitingPacket, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\7\0\0\0\0\0"
    "game.WaitingPacket"
    "message"
  }},
};

PROTOBUF_NOINLINE void WaitingPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:game.WaitingPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.waiting_number_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WaitingPacket::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WaitingPacket& this_ = static_cast<const WaitingPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WaitingPacket::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WaitingPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:game.WaitingPacket)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 waiting_number = 1;
          if (this_._internal_waiting_number() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_waiting_number(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "game.WaitingPacket.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:game.WaitingPacket)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WaitingPacket::ByteSizeLong(const MessageLite& base) {
          const WaitingPacket& this_ = static_cast<const WaitingPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WaitingPacket::ByteSizeLong() const {
          const WaitingPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:game.WaitingPacket)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // int32 waiting_number = 1;
            if (this_._internal_waiting_number() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_waiting_number());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WaitingPacket::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WaitingPacket*>(&to_msg);
  auto& from = static_cast<const WaitingPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game.WaitingPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_waiting_number() != 0) {
    _this->_impl_.waiting_number_ = from._impl_.waiting_number_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WaitingPacket::CopyFrom(const WaitingPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.WaitingPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WaitingPacket::InternalSwap(WaitingPacket* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.waiting_number_, other->_impl_.waiting_number_);
}

::google::protobuf::Metadata WaitingPacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace game
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_message_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
