// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf C++ Version: 5.29.3

#ifndef message_2eproto_2epb_2eh
#define message_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_message_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_message_2eproto;
namespace game {
class ChatPacket;
struct ChatPacketDefaultTypeInternal;
extern ChatPacketDefaultTypeInternal _ChatPacket_default_instance_;
class GamePacket;
struct GamePacketDefaultTypeInternal;
extern GamePacketDefaultTypeInternal _GamePacket_default_instance_;
class WaitingPacket;
struct WaitingPacketDefaultTypeInternal;
extern WaitingPacketDefaultTypeInternal _WaitingPacket_default_instance_;
}  // namespace game
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace game {
enum PacketType : int {
  NONE = 0,
  CHAT = 1,
  WAITING = 2,
  PacketType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PacketType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PacketType_IsValid(int value);
extern const uint32_t PacketType_internal_data_[];
constexpr PacketType PacketType_MIN = static_cast<PacketType>(0);
constexpr PacketType PacketType_MAX = static_cast<PacketType>(2);
constexpr int PacketType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
PacketType_descriptor();
template <typename T>
const std::string& PacketType_Name(T value) {
  static_assert(std::is_same<T, PacketType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PacketType_Name().");
  return PacketType_Name(static_cast<PacketType>(value));
}
template <>
inline const std::string& PacketType_Name(PacketType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PacketType_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool PacketType_Parse(absl::string_view name, PacketType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PacketType>(
      PacketType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class WaitingPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game.WaitingPacket) */ {
 public:
  inline WaitingPacket() : WaitingPacket(nullptr) {}
  ~WaitingPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WaitingPacket* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WaitingPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WaitingPacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline WaitingPacket(const WaitingPacket& from) : WaitingPacket(nullptr, from) {}
  inline WaitingPacket(WaitingPacket&& from) noexcept
      : WaitingPacket(nullptr, std::move(from)) {}
  inline WaitingPacket& operator=(const WaitingPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline WaitingPacket& operator=(WaitingPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WaitingPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const WaitingPacket* internal_default_instance() {
    return reinterpret_cast<const WaitingPacket*>(
        &_WaitingPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(WaitingPacket& a, WaitingPacket& b) { a.Swap(&b); }
  inline void Swap(WaitingPacket* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WaitingPacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WaitingPacket* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WaitingPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WaitingPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WaitingPacket& from) { WaitingPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WaitingPacket* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game.WaitingPacket"; }

 protected:
  explicit WaitingPacket(::google::protobuf::Arena* arena);
  WaitingPacket(::google::protobuf::Arena* arena, const WaitingPacket& from);
  WaitingPacket(::google::protobuf::Arena* arena, WaitingPacket&& from) noexcept
      : WaitingPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kWaitingNumberFieldNumber = 1,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // int32 waiting_number = 1;
  void clear_waiting_number() ;
  ::int32_t waiting_number() const;
  void set_waiting_number(::int32_t value);

  private:
  ::int32_t _internal_waiting_number() const;
  void _internal_set_waiting_number(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:game.WaitingPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      34, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const WaitingPacket& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::int32_t waiting_number_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class ChatPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game.ChatPacket) */ {
 public:
  inline ChatPacket() : ChatPacket(nullptr) {}
  ~ChatPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ChatPacket* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ChatPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ChatPacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline ChatPacket(const ChatPacket& from) : ChatPacket(nullptr, from) {}
  inline ChatPacket(ChatPacket&& from) noexcept
      : ChatPacket(nullptr, std::move(from)) {}
  inline ChatPacket& operator=(const ChatPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatPacket& operator=(ChatPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatPacket* internal_default_instance() {
    return reinterpret_cast<const ChatPacket*>(
        &_ChatPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ChatPacket& a, ChatPacket& b) { a.Swap(&b); }
  inline void Swap(ChatPacket* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatPacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatPacket* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ChatPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ChatPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ChatPacket& from) { ChatPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ChatPacket* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game.ChatPacket"; }

 protected:
  explicit ChatPacket(::google::protobuf::Arena* arena);
  ChatPacket(::google::protobuf::Arena* arena, const ChatPacket& from);
  ChatPacket(::google::protobuf::Arena* arena, ChatPacket&& from) noexcept
      : ChatPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kSessionIdFieldNumber = 1,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // int32 session_id = 1;
  void clear_session_id() ;
  ::int32_t session_id() const;
  void set_session_id(::int32_t value);

  private:
  ::int32_t _internal_session_id() const;
  void _internal_set_session_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:game.ChatPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      31, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ChatPacket& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::int32_t session_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class GamePacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game.GamePacket) */ {
 public:
  inline GamePacket() : GamePacket(nullptr) {}
  ~GamePacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GamePacket* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GamePacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GamePacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline GamePacket(const GamePacket& from) : GamePacket(nullptr, from) {}
  inline GamePacket(GamePacket&& from) noexcept
      : GamePacket(nullptr, std::move(from)) {}
  inline GamePacket& operator=(const GamePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline GamePacket& operator=(GamePacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GamePacket& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kChat = 2,
    kWaiting = 3,
    PAYLOAD_NOT_SET = 0,
  };
  static inline const GamePacket* internal_default_instance() {
    return reinterpret_cast<const GamePacket*>(
        &_GamePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GamePacket& a, GamePacket& b) { a.Swap(&b); }
  inline void Swap(GamePacket* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GamePacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GamePacket* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GamePacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GamePacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GamePacket& from) { GamePacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GamePacket* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game.GamePacket"; }

 protected:
  explicit GamePacket(::google::protobuf::Arena* arena);
  GamePacket(::google::protobuf::Arena* arena, const GamePacket& from);
  GamePacket(::google::protobuf::Arena* arena, GamePacket&& from) noexcept
      : GamePacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeFieldNumber = 1,
    kChatFieldNumber = 2,
    kWaitingFieldNumber = 3,
  };
  // .game.PacketType type = 1;
  void clear_type() ;
  ::game::PacketType type() const;
  void set_type(::game::PacketType value);

  private:
  ::game::PacketType _internal_type() const;
  void _internal_set_type(::game::PacketType value);

  public:
  // .game.ChatPacket chat = 2;
  bool has_chat() const;
  private:
  bool _internal_has_chat() const;

  public:
  void clear_chat() ;
  const ::game::ChatPacket& chat() const;
  PROTOBUF_NODISCARD ::game::ChatPacket* release_chat();
  ::game::ChatPacket* mutable_chat();
  void set_allocated_chat(::game::ChatPacket* value);
  void unsafe_arena_set_allocated_chat(::game::ChatPacket* value);
  ::game::ChatPacket* unsafe_arena_release_chat();

  private:
  const ::game::ChatPacket& _internal_chat() const;
  ::game::ChatPacket* _internal_mutable_chat();

  public:
  // .game.WaitingPacket waiting = 3;
  bool has_waiting() const;
  private:
  bool _internal_has_waiting() const;

  public:
  void clear_waiting() ;
  const ::game::WaitingPacket& waiting() const;
  PROTOBUF_NODISCARD ::game::WaitingPacket* release_waiting();
  ::game::WaitingPacket* mutable_waiting();
  void set_allocated_waiting(::game::WaitingPacket* value);
  void unsafe_arena_set_allocated_waiting(::game::WaitingPacket* value);
  ::game::WaitingPacket* unsafe_arena_release_waiting();

  private:
  const ::game::WaitingPacket& _internal_waiting() const;
  ::game::WaitingPacket* _internal_mutable_waiting();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:game.GamePacket)
 private:
  class _Internal;
  void set_has_chat();
  void set_has_waiting();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 3, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GamePacket& from_msg);
    int type_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::game::ChatPacket* chat_;
      ::game::WaitingPacket* waiting_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GamePacket

// .game.PacketType type = 1;
inline void GamePacket::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::game::PacketType GamePacket::type() const {
  // @@protoc_insertion_point(field_get:game.GamePacket.type)
  return _internal_type();
}
inline void GamePacket::set_type(::game::PacketType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:game.GamePacket.type)
}
inline ::game::PacketType GamePacket::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::game::PacketType>(_impl_.type_);
}
inline void GamePacket::_internal_set_type(::game::PacketType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// .game.ChatPacket chat = 2;
inline bool GamePacket::has_chat() const {
  return payload_case() == kChat;
}
inline bool GamePacket::_internal_has_chat() const {
  return payload_case() == kChat;
}
inline void GamePacket::set_has_chat() {
  _impl_._oneof_case_[0] = kChat;
}
inline void GamePacket::clear_chat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kChat) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.chat_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.chat_);
    }
    clear_has_payload();
  }
}
inline ::game::ChatPacket* GamePacket::release_chat() {
  // @@protoc_insertion_point(field_release:game.GamePacket.chat)
  if (payload_case() == kChat) {
    clear_has_payload();
    auto* temp = _impl_.payload_.chat_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.chat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::game::ChatPacket& GamePacket::_internal_chat() const {
  return payload_case() == kChat ? *_impl_.payload_.chat_ : reinterpret_cast<::game::ChatPacket&>(::game::_ChatPacket_default_instance_);
}
inline const ::game::ChatPacket& GamePacket::chat() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game.GamePacket.chat)
  return _internal_chat();
}
inline ::game::ChatPacket* GamePacket::unsafe_arena_release_chat() {
  // @@protoc_insertion_point(field_unsafe_arena_release:game.GamePacket.chat)
  if (payload_case() == kChat) {
    clear_has_payload();
    auto* temp = _impl_.payload_.chat_;
    _impl_.payload_.chat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GamePacket::unsafe_arena_set_allocated_chat(::game::ChatPacket* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_chat();
    _impl_.payload_.chat_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game.GamePacket.chat)
}
inline ::game::ChatPacket* GamePacket::_internal_mutable_chat() {
  if (payload_case() != kChat) {
    clear_payload();
    set_has_chat();
    _impl_.payload_.chat_ =
        ::google::protobuf::Message::DefaultConstruct<::game::ChatPacket>(GetArena());
  }
  return _impl_.payload_.chat_;
}
inline ::game::ChatPacket* GamePacket::mutable_chat() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::game::ChatPacket* _msg = _internal_mutable_chat();
  // @@protoc_insertion_point(field_mutable:game.GamePacket.chat)
  return _msg;
}

// .game.WaitingPacket waiting = 3;
inline bool GamePacket::has_waiting() const {
  return payload_case() == kWaiting;
}
inline bool GamePacket::_internal_has_waiting() const {
  return payload_case() == kWaiting;
}
inline void GamePacket::set_has_waiting() {
  _impl_._oneof_case_[0] = kWaiting;
}
inline void GamePacket::clear_waiting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kWaiting) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.waiting_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.waiting_);
    }
    clear_has_payload();
  }
}
inline ::game::WaitingPacket* GamePacket::release_waiting() {
  // @@protoc_insertion_point(field_release:game.GamePacket.waiting)
  if (payload_case() == kWaiting) {
    clear_has_payload();
    auto* temp = _impl_.payload_.waiting_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.waiting_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::game::WaitingPacket& GamePacket::_internal_waiting() const {
  return payload_case() == kWaiting ? *_impl_.payload_.waiting_ : reinterpret_cast<::game::WaitingPacket&>(::game::_WaitingPacket_default_instance_);
}
inline const ::game::WaitingPacket& GamePacket::waiting() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game.GamePacket.waiting)
  return _internal_waiting();
}
inline ::game::WaitingPacket* GamePacket::unsafe_arena_release_waiting() {
  // @@protoc_insertion_point(field_unsafe_arena_release:game.GamePacket.waiting)
  if (payload_case() == kWaiting) {
    clear_has_payload();
    auto* temp = _impl_.payload_.waiting_;
    _impl_.payload_.waiting_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GamePacket::unsafe_arena_set_allocated_waiting(::game::WaitingPacket* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_waiting();
    _impl_.payload_.waiting_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game.GamePacket.waiting)
}
inline ::game::WaitingPacket* GamePacket::_internal_mutable_waiting() {
  if (payload_case() != kWaiting) {
    clear_payload();
    set_has_waiting();
    _impl_.payload_.waiting_ =
        ::google::protobuf::Message::DefaultConstruct<::game::WaitingPacket>(GetArena());
  }
  return _impl_.payload_.waiting_;
}
inline ::game::WaitingPacket* GamePacket::mutable_waiting() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::game::WaitingPacket* _msg = _internal_mutable_waiting();
  // @@protoc_insertion_point(field_mutable:game.GamePacket.waiting)
  return _msg;
}

inline bool GamePacket::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void GamePacket::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline GamePacket::PayloadCase GamePacket::payload_case() const {
  return GamePacket::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ChatPacket

// int32 session_id = 1;
inline void ChatPacket::clear_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_ = 0;
}
inline ::int32_t ChatPacket::session_id() const {
  // @@protoc_insertion_point(field_get:game.ChatPacket.session_id)
  return _internal_session_id();
}
inline void ChatPacket::set_session_id(::int32_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:game.ChatPacket.session_id)
}
inline ::int32_t ChatPacket::_internal_session_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_id_;
}
inline void ChatPacket::_internal_set_session_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_ = value;
}

// string message = 2;
inline void ChatPacket::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& ChatPacket::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game.ChatPacket.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ChatPacket::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:game.ChatPacket.message)
}
inline std::string* ChatPacket::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:game.ChatPacket.message)
  return _s;
}
inline const std::string& ChatPacket::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void ChatPacket::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* ChatPacket::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* ChatPacket::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:game.ChatPacket.message)
  return _impl_.message_.Release();
}
inline void ChatPacket::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:game.ChatPacket.message)
}

// -------------------------------------------------------------------

// WaitingPacket

// int32 waiting_number = 1;
inline void WaitingPacket::clear_waiting_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.waiting_number_ = 0;
}
inline ::int32_t WaitingPacket::waiting_number() const {
  // @@protoc_insertion_point(field_get:game.WaitingPacket.waiting_number)
  return _internal_waiting_number();
}
inline void WaitingPacket::set_waiting_number(::int32_t value) {
  _internal_set_waiting_number(value);
  // @@protoc_insertion_point(field_set:game.WaitingPacket.waiting_number)
}
inline ::int32_t WaitingPacket::_internal_waiting_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.waiting_number_;
}
inline void WaitingPacket::_internal_set_waiting_number(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.waiting_number_ = value;
}

// string message = 2;
inline void WaitingPacket::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& WaitingPacket::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game.WaitingPacket.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void WaitingPacket::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:game.WaitingPacket.message)
}
inline std::string* WaitingPacket::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:game.WaitingPacket.message)
  return _s;
}
inline const std::string& WaitingPacket::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void WaitingPacket::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* WaitingPacket::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* WaitingPacket::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:game.WaitingPacket.message)
  return _impl_.message_.Release();
}
inline void WaitingPacket::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:game.WaitingPacket.message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace game


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::game::PacketType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::game::PacketType>() {
  return ::game::PacketType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // message_2eproto_2epb_2eh
